submap_service: "/elevation_mapping_long_range/get_grid_map"
update_rate: 2.0
robot_frame_id: "base"
map_frame_id: "map"
map_center_x: 0
map_center_y: 0
map_length_x: 4.0
map_length_y: 4.0
threshold: 0.02
bag_topic_name: "grid_map"

