length_in_x: 2.5
length_in_y: 2.5
position_x: 0.0
position_y: 0.0
resolution: 0.02
min_variance: 0.000001
max_variance: .inf
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.00000009
surface_normal_estimation_radius: 0.04
surface_normal_positive_axis: z
