length_in_x: 10
length_in_y: 70
position_x: 2.0
position_y: -30.0
resolution: 0.06
min_variance: 0.000009
max_variance: 0.01
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.0000009
surface_normal_estimation_radius: 0.05
surface_normal_positive_axis: z
