grid_map_visualizations:

  - name: elevation_change
    type: point_cloud
    params:
     layer: elevation_change

  - name: map_region
    type: map_region
    params:
     color: 16777215
     line_width: 0.003

