elevation_filters:
  # Edge detection on elevation layer with convolution filter as alternative to filter above.
 - name: edge_detection
   type: gridMapFilters/SlidingWindowMathExpressionFilter
   params:
     input_layer: elevation
     output_layer: edges
     expression: 'sumOfFinites([0,1,0;1,-4,1;0,1,0].*elevation)' # Edge detection.
     # expression: 'sumOfFinites([0,-1,0;-1,5,-1;0,-1,0].*elevation)' # Sharpen.
     compute_empty_cells: false
     edge_handling: mean # options: inside, crop, empty, mean
     window_size: 3 # Make sure to make this compatible with the kernel matrix.